### PR TITLE
Swift Package Manager support

### PR DESCRIPTION
**Pull request by martinpucik**
### Changes
- Added `Package.swift` to support Swift Package Manager without changes to project structure, so hopefully nothing will break for Cocoapods and Carthage 
- Changed imports in public header file

### Additional info

build, tests, analyze and `pod lib lint` were all green on my local machine, lets wait for CI and see if everything works

### CODE REVIEW

**Comment by Kaspik** [comment]
@garrettmoon / @jparise Hey! I know it might not be top priority, but we would love to use whole PINRemoteImage in module (framework) through SPM so we are ready to prepare it for SPM for you.

Martin started here, will continue with PINCache etc., but it would be nice if you could review this and stay up-to-date with our PRs and keep merging them if you think this is a good idea.

Thanks!

**Comment by jparise** [comment]
What sort of CI-level check should we have in place to verify that the packaging is (and remains) correct?

**Comment by martinpucik** [comment]
Hey @jparise thank you for taking a look at this!

I added test target to SPM to run current tests in the package too, that should help verify is behaving properly.

And I added an Example project and build step on CI where we can verify the Cocoapods integration is still working properly after adding SPM and making changes to PINOperation source.

Let me please know if you think any other checks or changes are necessary

**Comment by Kaspik** [comment]
@garrettmoon Thanks for merge! Would you mind bumping version and releasing new one + tag to make this available for PINCache and other parts as SPM already?

**Comment by jparise** [comment]
@Kaspik I think we'd be in a good place to release a new version once #31 is also addressed. That would give us good overall platform and packaging support.

**Comment by Kaspik** [comment]
@jparise https://github.com/pinterest/PINOperation/pull/31 merged as well, do you think we could release and tag new version for this? We would like to continue with SPM for PINCache and PINRemoteImage. :)

**Comment by garrettmoon** [comment]
Thank you both so much for the work! I'll get out a new release.

**Comment by garrettmoon** [comment]
Published!

**Pull request merged**
