### PR TITLE
Add Carthage for watchOS, dependent by PINCache

### PR DESCRIPTION
**Pull request by dreampiggy**
See: https://github.com/pinterest/PINCache/issues/268

@garrettmoon

### CODE REVIEW

**Comment by dreampiggy** [comment]
> Would you mind adding a test target for watchOS as well and we'll get this merged?

@garrettmoon  Xcode does not support both Unit Test or UI Test for watchOS.

If Xcode support watchOS test, I can add them...Seems you didn't realize this limit.

**Comment by garrettmoon** [comment]
I sure didn't! Thanks for the addition, merging now.

**Comment by dreampiggy** [comment]
Any release date for Carthage support ? So that I can update the PR for PINCache in https://github.com/pinterest/PINCache/pull/269

**Comment by dreampiggy** [comment]
Seems PINOperation does not release new version. PINCache's WatchOS target still broken. @garrettmoon

**Pull request merged**
